"""Canonical project and environment constants."""

PROJECT_NAME = "Autonomous Company Research & Report Generation Agent"

OPENAI_API_KEY_ENV = "OPENAI_API_KEY"
PINECONE_API_KEY_ENV = "PINECONE_API_KEY"
PINECONE_INDEX_NAME_ENV = "PINECONE_INDEX_NAME"
TAVILY_API_KEY_ENV = "TAVILY_API_KEY"
NEWS_API_KEY_ENV = "NEWS_API_KEY"
ALPHA_VANTAGE_API_KEY_ENV = "ALPHA_VANTAGE_API_KEY"
SEC_USER_AGENT_ENV = "SEC_USER_AGENT"

SEC_COMPANY_TICKERS_URL = "https://www.sec.gov/files/company_tickers.json"
