"""Canonical project and environment constants."""

PROJECT_NAME = "Autonomous Company Research & Report Generation Agent"

AGENT_API_KEY_ENV = "AGENT_API_KEY"
OPENAI_API_KEY_ENV = "OPENAI_API_KEY"
OPENAI_BASE_URL_ENV = "OPENAI_BASE_URL"
OPENAI_EMBEDDING_MODEL_ENV = "OPENAI_EMBEDDING_MODEL"
PINECONE_API_KEY_ENV = "PINECONE_API_KEY"
PINECONE_INDEX_NAME_ENV = "PINECONE_INDEX_NAME"
PINECONE_INDEX_HOST_ENV = "PINECONE_INDEX_HOST"
PINECONE_NAMESPACE_PREFIX_ENV = "PINECONE_NAMESPACE_PREFIX"
PINECONE_VECTOR_DIMENSION_ENV = "PINECONE_VECTOR_DIMENSION"
PINECONE_API_VERSION_ENV = "PINECONE_API_VERSION"
PINECONE_MAX_UPSERT_BATCH_SIZE_ENV = "PINECONE_MAX_UPSERT_BATCH_SIZE"
PINECONE_MAX_QUERY_TOP_K_ENV = "PINECONE_MAX_QUERY_TOP_K"
TAVILY_API_KEY_ENV = "TAVILY_API_KEY"
NEWS_API_KEY_ENV = "NEWS_API_KEY"
ALPHA_VANTAGE_API_KEY_ENV = "ALPHA_VANTAGE_API_KEY"
SEC_USER_AGENT_ENV = "SEC_USER_AGENT"

SEC_COMPANY_TICKERS_URL = "https://www.sec.gov/files/company_tickers.json"

NEWS_API_BASE_URL = "https://newsapi.org/v2"
NEWS_API_EVERYTHING_URL = f"{NEWS_API_BASE_URL}/everything"
NEWS_API_DEFAULT_LANGUAGE = "en"
NEWS_API_DEFAULT_SORT_BY = "publishedAt"
NEWS_API_DEFAULT_PAGE_SIZE = 20
NEWS_API_MAX_PAGE_SIZE = 100
NEWS_API_DEFAULT_LOOKBACK_DAYS = 7

OPENAI_BASE_URL = "https://api.openai.com/v1"
OPENAI_EMBEDDINGS_URL = f"{OPENAI_BASE_URL}/embeddings"
OPENAI_DEFAULT_EMBEDDING_MODEL = "text-embedding-3-small"
OPENAI_MAX_EMBEDDING_BATCH_SIZE = 16

PINECONE_DEFAULT_NAMESPACE_PREFIX = "company"
PINECONE_DEFAULT_VECTOR_DIMENSION = 1536
PINECONE_DEFAULT_MAX_UPSERT_BATCH_SIZE = 100
PINECONE_DEFAULT_MAX_QUERY_TOP_K = 10

TAVILY_BASE_URL = "https://api.tavily.com"
TAVILY_SEARCH_URL = f"{TAVILY_BASE_URL}/search"
TAVILY_DEFAULT_TOPIC = "general"
TAVILY_DEFAULT_MAX_RESULTS = 5
TAVILY_MAX_RESULTS = 10
TAVILY_DEFAULT_LOOKBACK_DAYS = 30
TAVILY_MAX_LOOKBACK_DAYS = 365
