"""Canonical project and environment constants."""

PROJECT_NAME = "Autonomous Company Research & Report Generation Agent"

OPENAI_API_KEY_ENV = "OPENAI_API_KEY"
PINECONE_API_KEY_ENV = "PINECONE_API_KEY"
PINECONE_INDEX_NAME_ENV = "PINECONE_INDEX_NAME"
TAVILY_API_KEY_ENV = "TAVILY_API_KEY"
NEWS_API_KEY_ENV = "NEWS_API_KEY"
ALPHA_VANTAGE_API_KEY_ENV = "ALPHA_VANTAGE_API_KEY"
SEC_USER_AGENT_ENV = "SEC_USER_AGENT"

SEC_COMPANY_TICKERS_URL = "https://www.sec.gov/files/company_tickers.json"

NEWS_API_BASE_URL = "https://newsapi.org/v2"
NEWS_API_EVERYTHING_URL = f"{NEWS_API_BASE_URL}/everything"
NEWS_API_DEFAULT_LANGUAGE = "en"
NEWS_API_DEFAULT_SORT_BY = "publishedAt"
NEWS_API_DEFAULT_PAGE_SIZE = 20
NEWS_API_MAX_PAGE_SIZE = 100
NEWS_API_DEFAULT_LOOKBACK_DAYS = 7
